import turtle 
turtle.Turtle()
turtle.title("my drawing")
turtle.bgcolor("black")
turtle.pencolor("blue")
turtle.pensize(4)
turtle.speed(2)

turtle.penup()
turtle.goto(-150,-20)
turtle.pendown()
turtle.left(90)
turtle.forward(100)
turtle.right(135)
turtle.forward(50)
turtle.right(90)
turtle.backward(50)
turtle.right(135)
turtle.backward(100)
# turtle.pencolor("black")
turtle.penup()
turtle.right(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(100)
turtle.pendown()
# turtle.pencolor("blue")
turtle.right(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(70)
turtle.right(90)
turtle.backward(100)
turtle.penup()
turtle.left(90)
turtle.forward(10)
turtle.pendown()
turtle.right(90)
turtle.forward(100)
turtle.penup()
turtle.left(180)
turtle.forward(45)
turtle.pendown()
turtle.right(45)
turtle.forward(70)
turtle.penup()
turtle.left(180)
turtle.forward(70)
turtle.pendown()
turtle.left(90)
turtle.forward(65)
turtle.penup()
turtle.left(45)
turtle.forward(50)
turtle.pendown()

turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(40)
turtle.penup()
turtle.right(180)
turtle.forward(40)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(50)
turtle.penup()
turtle.left(180)
turtle.forward(25)
turtle.pendown()
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(25)
turtle.penup()
turtle.right(180)
turtle.forward(25)
turtle.pendown()
turtle.forward(25)





turtle.hideturtle()
turtle.mainloop()